# Site settings
title: Cam Pedersen
email: cam@campedersen.com
description: ""
baseurl: ""
url: "http://campedersen.com"

# Build settings
#markdown: kramdown
permalink: pretty

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
